# Generated by Django 6.0.4 on 2026-04-22 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_category_listeninghistory_queueitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('message', models.CharField(max_length=260)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=220)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.CharField(blank=True, max_length=260)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=180)),
                ('meta_description', models.TextField(blank=True, max_length=320)),
                ('is_published', models.BooleanField(default=True)),
                ('show_in_footer', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'الرئيسية'), ('discover', 'اكتشف'), ('charts', 'الأكثر استماعًا'), ('library', 'مكتبتي'), ('favorites', 'المفضلة'), ('search', 'بحث'), ('artists', 'الفنانون'), ('albums', 'الألبومات'), ('categories', 'التصنيفات'), ('playlists', 'قوائم التشغيل'), ('login', 'تسجيل الدخول'), ('signup', 'إنشاء حساب'), ('legal_pages', 'الصفحات القانونية')], max_length=80, unique=True)),
                ('browser_title', models.CharField(max_length=180)),
                ('meta_description', models.TextField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('og_title', models.CharField(blank=True, max_length=180)),
                ('og_description', models.TextField(blank=True, max_length=320)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('noindex', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='نغم', max_length=120)),
                ('tagline', models.CharField(default='صوت بلا موسيقى', max_length=200)),
                ('default_title', models.CharField(default='نغم - منصة صوت بلا موسيقى', max_length=180)),
                ('default_description', models.TextField(default='استمع إلى أناشيد وقصائد ومقاطع صوتية نظيفة بلا موسيقى.')),
                ('default_keywords', models.CharField(blank=True, help_text='افصل الكلمات بفواصل.', max_length=300)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('canonical_domain', models.URLField(blank=True, help_text='مثال: https://nagham.example.com')),
                ('analytics_code', models.TextField(blank=True, help_text='كود Analytics اختياري.')),
                ('header_cta_label', models.CharField(default='تسجيل', max_length=80)),
                ('header_cta_url', models.CharField(default='/signup/', max_length=200)),
                ('maintenance_message', models.CharField(blank=True, max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=600)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
