# Generated by Django 6.0.4 on 2026-04-23 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_announcement_faq_legalpage_seopage_sitesettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'الرئيسية'), ('discover', 'اكتشف'), ('charts', 'الأكثر استماعًا'), ('library', 'مكتبتي'), ('favorites', 'المفضلة'), ('search', 'البحث'), ('artists', 'الفنانون'), ('artist_detail', 'صفحة الفنان'), ('albums', 'الألبومات'), ('album_detail', 'صفحة الألبوم'), ('categories', 'التصنيفات'), ('category_detail', 'صفحة التصنيف'), ('playlists', 'قوائم التشغيل'), ('playlist_detail', 'صفحة قائمة التشغيل'), ('track_detail', 'صفحة المقطع'), ('login', 'تسجيل الدخول'), ('signup', 'إنشاء حساب'), ('profile_detail', 'الملف الشخصي'), ('profile_edit', 'تعديل الملف الشخصي'), ('legal_pages', 'الصفحات القانونية'), ('legal_page_detail', 'صفحة قانونية')], max_length=80, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, max_length=320)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('primary_label', models.CharField(blank=True, max_length=80)),
                ('primary_url', models.CharField(blank=True, max_length=200)),
                ('secondary_label', models.CharField(blank=True, max_length=80)),
                ('secondary_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page banner',
                'verbose_name_plural': 'Page banners',
                'ordering': ['page_key'],
            },
        ),
        migrations.AlterField(
            model_name='seopage',
            name='page_key',
            field=models.CharField(choices=[('home', 'الرئيسية'), ('discover', 'اكتشف'), ('charts', 'الأكثر استماعًا'), ('library', 'مكتبتي'), ('favorites', 'المفضلة'), ('search', 'البحث'), ('artists', 'الفنانون'), ('artist_detail', 'صفحة الفنان'), ('albums', 'الألبومات'), ('album_detail', 'صفحة الألبوم'), ('categories', 'التصنيفات'), ('category_detail', 'صفحة التصنيف'), ('playlists', 'قوائم التشغيل'), ('playlist_detail', 'صفحة قائمة التشغيل'), ('track_detail', 'صفحة المقطع'), ('login', 'تسجيل الدخول'), ('signup', 'إنشاء حساب'), ('profile_detail', 'الملف الشخصي'), ('profile_edit', 'تعديل الملف الشخصي'), ('legal_pages', 'الصفحات القانونية'), ('legal_page_detail', 'صفحة قانونية')], max_length=80, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='profiles/banners/')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='music_userp_created_03d584_idx'), models.Index(fields=['is_published'], name='music_userp_is_publ_b11e1d_idx')],
            },
        ),
    ]
