# Generated by Codex on 2026-04-23

from django.db import migrations, models


BANNER_IMAGE_WARM = "https://images.unsplash.com/photo-1579546928937-641f7ac9bced?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MjR8fHxlbnwwfHx8fHw%3D&ixlib=rb-4.1.0&q=60&w=3000"
BANNER_IMAGE_COOL = "https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MTJ8fHxlbnwwfHx8fHw%3D&ixlib=rb-4.1.0&q=60&w=3000"
BANNER_IMAGE_LIGHT = "https://images.unsplash.com/photo-1523821741446-edb2b68bb7a0?auto=format&fit=crop&fm=jpg&ixid=M3wxMjA3fDB8MHxleHBsb3JlLWZlZWR8MzF8fHxlbnwwfHx8fHw%3D&ixlib=rb-4.1.0&q=60&w=3000"


PAGE_BANNER_DEFAULTS = {
    "home": {"eyebrow": "منصة نغم", "title": "مكتبة صوتية نظيفة بروح كلاسيكية.", "description": "استمع واكتشف واحتفظ بالمقاطع والمنشورات في تجربة عربية أنيقة.", "image_url": BANNER_IMAGE_WARM},
    "discover": {"eyebrow": "اكتشاف", "title": "اختيارات متجددة كل زيارة.", "description": "تجول بين المقاطع والتصنيفات والوجوه الجديدة في تجربة سريعة وواضحة.", "image_url": BANNER_IMAGE_COOL},
    "charts": {"eyebrow": "الترند الهادئ", "title": "الأكثر حضورًا هذا الوقت.", "description": "تابع المقاطع الأعلى استماعًا داخل المنصة.", "image_url": BANNER_IMAGE_COOL},
    "library": {"eyebrow": "مساحتك الخاصة", "title": "كل ما حفظته في مكان واحد.", "description": "المحفوظات والطابور وقوائم التشغيل ومنشوراتك الشخصية.", "image_url": BANNER_IMAGE_WARM},
    "favorites": {"eyebrow": "المفضلة", "title": "مقاطعك الأقرب إليك.", "description": "الوصول السريع إلى كل ما نال إعجابك.", "image_url": BANNER_IMAGE_LIGHT},
    "search": {"eyebrow": "بحث", "title": "اعثر على ما تريد بدقة.", "description": "ابحث بالاسم أو الوصف أو المنشد أو كلمات المقطع.", "image_url": BANNER_IMAGE_LIGHT},
    "artists": {"eyebrow": "فنانون", "title": "تصفح الأصوات والمنشدين.", "description": "تعرف على الفنانين وابدأ رحلتك معهم.", "image_url": BANNER_IMAGE_COOL},
    "artist_detail": {"eyebrow": "فنان", "title": "نبذة ومسيرة ومقاطع الفنان.", "description": "صفحة تجمع الألبومات والمقاطع والهوية البصرية للفنان.", "image_url": BANNER_IMAGE_COOL},
    "albums": {"eyebrow": "ألبومات", "title": "إصدارات متسلسلة بنَفَس كلاسيكي.", "description": "استعرض الألبومات وتفاصيل كل إصدار.", "image_url": BANNER_IMAGE_WARM},
    "album_detail": {"eyebrow": "ألبوم", "title": "تفاصيل الإصدار ومحتواه.", "description": "غلاف الألبوم ووصفه ومقاطع الاستماع داخله.", "image_url": BANNER_IMAGE_WARM},
    "categories": {"eyebrow": "تصنيفات", "title": "رتب مزاجك قبل الاستماع.", "description": "انتقل بين الأنواع والتوجهات بسهولة.", "image_url": BANNER_IMAGE_LIGHT},
    "category_detail": {"eyebrow": "تصنيف", "title": "مقاطع من نفس الطابع.", "description": "مجموعة مركزة تسهّل عليك اختيار ما يناسبك.", "image_url": BANNER_IMAGE_LIGHT},
    "playlists": {"eyebrow": "قوائم التشغيل", "title": "قوائم عامة من المجتمع.", "description": "استعرض القوائم المنشورة من المستخدمين.", "image_url": BANNER_IMAGE_COOL},
    "playlist_detail": {"eyebrow": "قائمة تشغيل", "title": "استماع مرتب وجاهز.", "description": "كل المقاطع المرتبطة داخل قائمة واحدة.", "image_url": BANNER_IMAGE_COOL},
    "track_detail": {"eyebrow": "الآن يعرض", "title": "معلومات المقطع والتفاعل حوله.", "description": "استمع وعلّق واحفظ وأضف إلى قوائمك.", "image_url": BANNER_IMAGE_WARM},
    "login": {"eyebrow": "عودة سريعة", "title": "ادخل إلى حسابك.", "description": "تابع مكتبتك ومنشوراتك وتفضيلاتك فورًا.", "image_url": BANNER_IMAGE_LIGHT},
    "signup": {"eyebrow": "حساب جديد", "title": "ابدأ حضورك داخل نغم.", "description": "أنشئ حسابًا وخصص ملفك الشخصي وانشر أفكارك.", "image_url": BANNER_IMAGE_LIGHT},
    "profile_detail": {"eyebrow": "الملف الشخصي", "title": "صورتك ونبذتك ومنشوراتك.", "description": "صفحة شخصية قابلة للتخصيص والمشاركة.", "image_url": BANNER_IMAGE_COOL},
    "profile_edit": {"eyebrow": "تخصيص الحساب", "title": "حدّث هويتك داخل المنصة.", "description": "ارفع الصورة الشخصية والبنر وعدّل الوصف والروابط.", "image_url": BANNER_IMAGE_LIGHT},
    "legal_pages": {"eyebrow": "قانوني", "title": "معلومات وسياسات المنصة.", "description": "كل الصفحات القانونية والأسئلة المتكررة في مكان واحد.", "image_url": BANNER_IMAGE_LIGHT},
    "legal_page_detail": {"eyebrow": "صفحة قانونية", "title": "تفاصيل الصفحة القانونية.", "description": "اقرأ النص الكامل للسياسات والشروط.", "image_url": BANNER_IMAGE_LIGHT},
}


def seed_page_banners(apps, schema_editor):
    PageBanner = apps.get_model("music", "PageBanner")

    for page_key, defaults in PAGE_BANNER_DEFAULTS.items():
        banner, created = PageBanner.objects.get_or_create(
            page_key=page_key,
            defaults={
                "eyebrow": defaults["eyebrow"],
                "title": defaults["title"],
                "description": defaults["description"],
                "image_url": defaults["image_url"],
                "is_active": True,
            },
        )
        if created:
            continue

        changed = False
        if not banner.eyebrow:
            banner.eyebrow = defaults["eyebrow"]
            changed = True
        if not banner.title:
            banner.title = defaults["title"]
            changed = True
        if not banner.description:
            banner.description = defaults["description"]
            changed = True
        if not banner.image and not banner.image_url:
            banner.image_url = defaults["image_url"]
            changed = True

        if changed:
            banner.save(update_fields=["eyebrow", "title", "description", "image_url", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_pagebanner_alter_seopage_page_key_userprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagebanner",
            name="image_url",
            field=models.URLField(blank=True, help_text="رابط صورة مباشر من الإنترنت (اختياري)."),
        ),
        migrations.RunPython(seed_page_banners, migrations.RunPython.noop),
    ]
