# Generated by Django 6.0.4 on 2026-04-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_userpost_shared_track_likes_postcomment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postcomment',
            new_name='music_postc_created_8c5513_idx',
            old_name='music_postc_created_62066f_idx',
        ),
        migrations.RenameIndex(
            model_name='postcomment',
            new_name='music_postc_is_visi_e3be6f_idx',
            old_name='music_postc_is_visi_63cb80_idx',
        ),
    ]
