# Generated by Django 5.2 on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0013_pagebanner_slots_and_sizes"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredMediaFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_key", models.CharField(max_length=500, unique=True)),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=120)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("content", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["file_key"],
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="custom_head_code",
            field=models.TextField(blank=True, help_text="Any verification or analytics tags rendered inside head."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="google_site_verification",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="verification_file_content",
            field=models.TextField(blank=True, help_text="Content returned by the verification file endpoint."),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="verification_file_name",
            field=models.CharField(blank=True, help_text="Example: google1234567890abcdef.html", max_length=255),
        ),
    ]
