# Generated by Django 6.0.4 on 2026-04-29 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_storedmediafile_and_site_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagebanner',
            options={'ordering': ['page_key', 'placement', 'sort_order', 'id'], 'verbose_name': 'Page banner', 'verbose_name_plural': 'Page banners'},
        ),
        migrations.RenameIndex(
            model_name='blockedip',
            new_name='music_block_ip_addr_62e52d_idx',
            old_name='music_block_ip_addr_62014e_idx',
        ),
        migrations.RenameIndex(
            model_name='blockedip',
            new_name='music_block_expires_ed27ca_idx',
            old_name='music_block_expires_77d4b4_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='music_secur_ip_addr_2e185f_idx',
            old_name='music_secur_ip_addr_4bb9ee_idx',
        ),
        migrations.RenameIndex(
            model_name='securityevent',
            new_name='music_secur_severit_8964fb_idx',
            old_name='music_secur_severi_1fe4d7_idx',
        ),
        migrations.RenameIndex(
            model_name='visitevent',
            new_name='music_visit_visited_be820b_idx',
            old_name='music_visit_visited_23f4f7_idx',
        ),
        migrations.RenameIndex(
            model_name='visitevent',
            new_name='music_visit_ip_addr_b50548_idx',
            old_name='music_visit_ip_addr_9f6b90_idx',
        ),
        migrations.RenameIndex(
            model_name='visitevent',
            new_name='music_visit_country_3d8a28_idx',
            old_name='music_visit_country_87d2de_idx',
        ),
        migrations.RenameIndex(
            model_name='visitevent',
            new_name='music_visit_path_05e5a0_idx',
            old_name='music_visit_path_1da02c_idx',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_description',
            field=models.TextField(default='نغَم منصة تقدّم لك الأغاني بصوت صافي 100% بدون موسيقى. اسمع صوت المغني الحقيقي بجودة عالية للمتعة أو للمونتاج وصناعة المحتوى.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_keywords',
            field=models.CharField(blank=True, default='نغَم, أغاني بدون موسيقى, أكابيلا عربي, Acapella, صوت صافي, صوت المغني الحقيقي, مونتاج, صناعة محتوى, أغاني للمونتاج, أغاني أكابيلا', help_text='افصل الكلمات بفواصل.', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_title',
            field=models.CharField(default='نغَم | أغاني بدون موسيقى بصوت صافي 100%', max_length=180),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_cta_label',
            field=models.CharField(default='جرّب الآن', max_length=80),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='نغَم', max_length=120),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='الأغاني بصوت صافي 100% — بدون موسيقى', max_length=200),
        ),
    ]
